### ISSUE TITLE
Where can I find the testing data?

### ISSUE THREAD

**Issue by timvieira** [surajiyer96/2IMW20-IBJS#1]
Thanks for sharing this code.  I'm trying to run it and I encountered an issue with data files (cf. error message below).  Could you please point me to where I might download them?  (It may be helpful to add a README file 🙂)  Thanks, in advance!
```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from Algorithms import *
  File "/home/timv/Desktop/Database-SQL-joins-algorithm-master/Algorithms.py", line 5, in <module>
    from QueryGraph import *
  File "/home/timv/Desktop/Database-SQL-joins-algorithm-master/QueryGraph.py", line 1, in <module>
    import DataLoader
  File "/home/timv/Desktop/Database-SQL-joins-algorithm-master/DataLoader.py", line 21, in <module>
    with open(data_loc + 'csv_schema.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/csv_schema.txt'
```

**Comment by bvdvecht** [comment]
Hi, this code was made in the context of a project for a university course on database technology. Therefore we did not spend much time on making it easily usable for the wider public. If I remember correctly, we used a database from the IMDb website for testing. Unfortunately I don't have these files any more, and also do not know exactly how we got it. Maybe one of the other authors still has them, though.

In any case, the data files might have been customized by us to be convenient to use for our specific case. I cannot guarantee the current code works at all with any given data file.

Regardless, I hope this code is somehow still useful for you.

**Comment by timvieira** [comment]
Oh, that's disappointing. Thanks for sharing anyways!
